[workspace]
authors = ["Karson Chrispens <karson.chrispens@ucsf.edu>"]
channels = ["conda-forge"]
name = "simulation_timeseries_optim"
platforms = ["osx-arm64", "linux-64]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9,<3.14"
jax = ">=0.7.2,<0.8"
optax = ">=0.2.6,<0.3"
reciprocalspaceship = "*"
setuptools = "*"
